CREATE SEQUENCE IF NOT EXISTS menu_items_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE cart_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id      BIGINT,
    menu_item_id BIGINT,
    quantity     INTEGER,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id UUID,
    status      VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE menu_items
(
    id            BIGINT NOT NULL,
    name          VARCHAR(255),
    price         DECIMAL,
    description   VARCHAR(255),
    image_url     VARCHAR(255),
    category      VARCHAR(255),
    restaurant_id UUID,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_menu_items PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT,
    menu_item_id BIGINT,
    quantity     INTEGER,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    staus          VARCHAR(255),
    payment_method VARCHAR(255),
    table_number   SMALLINT,
    customer_id    UUID,
    restaurant_id  UUID,
    total_price    DECIMAL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE restaurants
(
    id                 UUID         NOT NULL,
    name               VARCHAR(255),
    contact_number     VARCHAR(255) NOT NULL,
    owner_name         VARCHAR(255),
    location           VARCHAR(255),
    owner_phone_number VARCHAR(10),
    owner_email        VARCHAR(255) NOT NULL,
    type               VARCHAR(255),
    cuisine_type       VARCHAR(255),
    opening_hours      VARCHAR(255),
    image_url          VARCHAR(255) NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_restaurants PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           UUID         NOT NULL,
    first_name   VARCHAR(255) NOT NULL,
    last_name    VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    phone_number VARCHAR(10)  NOT NULL,
    national_id  VARCHAR(16)  NOT NULL,
    password     VARCHAR(255) NOT NULL,
    role         VARCHAR(255) NOT NULL,
    enabled      BOOLEAN      NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE restaurants
    ADD CONSTRAINT uc_restaurants_contactnumber UNIQUE (contact_number);

ALTER TABLE restaurants
    ADD CONSTRAINT uc_restaurants_owneremail UNIQUE (owner_email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_nationalid UNIQUE (national_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

CREATE UNIQUE INDEX idx_user_email_unq ON users (email);

CREATE UNIQUE INDEX idx_user_nationalid_unq ON users (national_id);

CREATE UNIQUE INDEX idx_user_phonenumber_unq ON users (phone_number);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_MENU_ITEM FOREIGN KEY (menu_item_id) REFERENCES menu_items (id);

ALTER TABLE menu_items
    ADD CONSTRAINT FK_MENU_ITEMS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_MENU_ITEM FOREIGN KEY (menu_item_id) REFERENCES menu_items (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);